CREATE TABLE Barang (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price INT UNSIGNED NOT NULL,
    category VARCHAR(50) NOT NULL
);

CREATE TABLE Transaksi (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL
);

CREATE TABLE DetailBarang (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    transaksi_id INTEGER NOT NULL,
    barang_id INTEGER NOT NULL,
    quantity INT UNSIGNED NOT NULL,

    FOREIGN KEY (transaksi_id) REFERENCES Transaksi(id) ON DELETE CASCADE,
    FOREIGN KEY (barang_id) REFERENCES Barang(id) ON DELETE CASCADE
);
