# Generated by Django 5.2.1 on 2025-05-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailbarang',
            name='date_transaksi',
        ),
    ]
